### PR TITLE
Modification of twitterbeat.template.json

### PR DESCRIPTION
**Pull request by rdrgporto**
Hi,

I have added the new modification to **twitterbeat.template.json**.

Regards

### CODE REVIEW

**Comment by buehler** [comment]
Hey I looked at the PR, why do you delete all the other mappings? Is there any particular reason for this?

I'd like the template to contain all the mappings I did _and_ the raw field from you.

**Comment by buehler** [comment]
(Same applies for the other PR with the awesome dashboard :)

**Comment by rdrgporto** [comment]
Hi,

I have tried another again with your template (original) with my dashboard and it works great,so you don't have modifiy your template :smile:.

Regarding Dashboards, I am working with the visualizations, I would like to obtain more information, for example as your template as my template I can't obtain nothing information about user (name,location,account..etc). I add an example:



One question, when you start twitterbeat, it creates a **twittermap.json**, is there any way to set the path? (In Filebeat one can set the path where create _.filebeat_).

Regards

**Comment by buehler** [comment]
For the `twittermap.json`: there is actually no possibility to set the path, sadly :-)

**Comment by buehler** [comment]
For the `twittermap.json`: there is actually no possibility to set the path, sadly :-)

**Pull request merged**
